services:
  - type: web
    name: n8n-ocr-kaizen
    env: python
    buildCommand: |
      apt-get update && \
      apt-get install -y tesseract-ocr poppler-utils && \
      pip install -r requirements.txt
    startCommand: gunicorn api:app
    plan: free
